### ISSUE TITLE
Implications of hapi 9.0.0 for MrHorse

### ISSUE THREAD

**Issue by devinivy** [mark-bradshaw/mrhorse#16]
It looks like hapi is aiming to provide lifecycle hooks on routes: https://github.com/hapijs/hapi/issues/2566.  This is wonderful, and will be able to offer performance that is hard to achieve in the form of a plugin due to access to hapi internals.  In some ways it's also very validating for MrHorse!

I'm wondering what we think this could mean for the feature-set of MrHorse.  If there's a "native" way to add lifecycle hooks per route, the interface/usage/benefits of MrHorse may look quite different in the future!  Just wanted to bring this up, and hopefully get some ideas going.

**Comment by mark-bradshaw** [comment]
Thanks for the heads up Devin.  That's very interesting.  If nothing else it could make it more straightforward for us to hook policies up.

**Comment by dlong500** [comment]
So now that hapi v9 is released is this plugin still compatible or are there changes required?

**Comment by mark-bradshaw** [comment]
@dlong500 I haven't tested yet, but I believe it should still work just fine.  I'll try to verify tonight.

**Comment by mark-bradshaw** [comment]
@dlong500 Good news.  I did a quick test and there's no problems.  MrHorse continues to work normally in Hapi 9 with no adjustments needed.
