### ISSUE TITLE
Dynamic functions

### ISSUE THREAD

**Issue by jlouazel** [mark-bradshaw/mrhorse#19]
Hi guys,

First of all, nice job, I really appreciate what you did. I just have a problem to make policies work dynamically as functions. I don't understand why because I entirely followed your example. Did anything change since the documentation was written?

Thanks,

**Comment by devinivy** [comment]
Ah, the changes have not been published yet.  I expect you will be able to use functions in the upcoming 1.2.0 release.  Sorry if this was unclear!

**Comment by mark-bradshaw** [comment]
Yes.  So sorry about the confusion there.  The master branch is about ready to head out the door as a new version but you caught it just before it did.  It should be published today.

**Comment by mark-bradshaw** [comment]
V 1.2.0 is winging it's way to npm right now.  It should be ready to go.

**Comment by jlouazel** [comment]
Actually, it works like a charm now. Thank you for the quick answer!

**Comment by mark-bradshaw** [comment]
All thanks go to @devinivy for his awesome work on parallels and dynamic
policies!

**Comment by devinivy** [comment]
Cheers, cheers!  Glad to see this published :) It was a breeze working on it with you, @mark-bradshaw.  Hopefully I'll be able to write the parallels example (#11) this afternoon.

**Comment by mark-bradshaw** [comment]
Thank you sir.
