### ISSUE TITLE
Turn on lab linting and fix style issues

### ISSUE THREAD

**Issue by mark-bradshaw** [mark-bradshaw/mrhorse#20]
lab -L

**Comment by devinivy** [comment]
`npm test` was reporting linting errors to me as I worked on 1.2.0.

**Comment by mark-bradshaw** [comment]
Odd. Mine wasn't and I double checked before sending it out. I'm on the
road right now. I'll take a look when I get back.

**Comment by mark-bradshaw** [comment]
Oh, oops.  I need to get my head engaged.  You're right.  I already turned on linting.  Bleh.  Closing this.
