### ISSUE TITLE
Cache handlers per route

### ISSUE THREAD

**Issue by devinivy** [mark-bradshaw/mrhorse#22]
Upon running a route, it would be nice to cache the policies to be run on each apply point for that route.  The cache can be keyed by `sort(methods)::path`. Unknown if the sorting is required, or if hapi already sorts it for this exact reason.  It would also be nice to create something like a `MrHorse.warmPolicies(server)` method that can be called to generate this cache whenever a developer sees fit (say, once the developer registers all routes).

**Comment by devinivy** [comment]
@mark-bradshaw what do you think about computing the policies to be run for each route during `onPreStart`?  This would remove the need to gradually generate a cache as the routes are used, and it would eliminate the need for a `warmPolicies` method, which I don't particularly love anyway.  Seems cleaner and more performant.  This would create a hard peer dependency of hapi 9+.

**Comment by mark-bradshaw** [comment]
Sounds reasonable.  We can do a major version bump to account for the hapi dependency change.

**Comment by devinivy** [comment]
Let's think of anything else we'd like to fit in to the major bump!
