### ISSUE TITLE
Can I specify universal policies?

### ISSUE THREAD

**Issue by McOmghall** [mark-bradshaw/mrhorse#3]
Is there a way to tell mrhorse I want a policy applied to every route? Combined with a negative policy expression ("don't apply policy x to route y") It could be very powerful.

**Comment by mark-bradshaw** [comment]
@McOmghall  I apologize for the lack of response.  I missed a notification on this.  

There isn't currently any code that acts the way you describe.  I'm happy to entertain PRs.
