### ISSUE TITLE
Pass information to policies

### ISSUE THREAD

**Issue by tjsail33** [mark-bradshaw/mrhorse#4]
Is there a way to pass information to policies? I have a database connection (essentially) that I would like to pass to the policies once it has been started in the main app logic, as reinstantiating it in the policies would cause new pools of connections to be started.

**Comment by mark-bradshaw** [comment]
@tjsail33,

Each policy gets passed the Hapi request object.  The request object has a couple spots that might be useful.  Request.app is a good spot to store app specific info, like db connection objects, so you could stash you db connection there.

```
var db = DB.connect(); // or something
server.app.db = db;
```

Or if you are using plugins to encapsulate your data you can get to your plugin with request.server.plugins.<your db plugin name>.xxx

So, the basic answer is look in the request object to reach to wherever you want to store you app specific stuff.
