### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by dlong500** [mark-bradshaw/mrhorse#7]
Is this project being maintained?  Especially with Hapi's rapid development pace I'm a bit afraid to get dependent on something that could become incompatible.  Maybe there just haven't been any changes needed recently but I'm a bit wary with the last commit being 5 months ago.

**Comment by mark-bradshaw** [comment]
@dlong500 Hi Davison.  It's being actively maintained.  I haven't had a need for an update in a while, but some issues have just come up that will make for some updates.  I also run on an open-open source model so anyone who contributes to the code base becomes a collaborator and can work on the code base.  If you think this is a good addition to Hapi jump in and it can be yours too. :)

**Comment by dlong500** [comment]
Ok, good to know.  I had been looking into hapi prerequisites but found them to be somewhat complicated, and as your docs mentioned they are also more limited than your plugin.  Thanks!

**Comment by mark-bradshaw** [comment]
You're welcome.
