### ISSUE TITLE
reply.redirect as next param

### ISSUE THREAD

**Issue by PavelPolyakov** [mark-bradshaw/mrhorse#8]
Hi,

What I want to do is to redirect the customer, when some policy does not match.
What I'm trying to do:

```
return next(reply.redirect('/auth'),false);
```

It doesn't work:
![image](https://cloud.githubusercontent.com/assets/839290/7678780/0925c5b2-fd57-11e4-8d67-c11d5e809f02.png)

However, this works:
```
return reply.redirect('/auth');
```

Question - is there any way to match the redirect with ```next()``` ?

**Comment by mark-bradshaw** [comment]
Hi @PavelPolyakov.  Thanks for bringing up this use case.  It's a little different than I anticipated, which is causing you problems, but I think we can accomodate this use case and others like it.  Basically what I need to do is, before I do any auto-responding based on errors that have been passed back in, to make sure a reply hasn't already been sent.

I would change the code at line 46 to be like this:
```
       if (!reply._replied) {
            if (err) {
                return reply(err);
            }

            reply.continue();
        }
```

That would allow you to do your own custom response in your policy and still let mrhorse know not to continue.  How's that?

**Comment by PavelPolyakov** [comment]
@mark-bradshaw 
yep, this works fine.

would be happy if you update the source :)

**Comment by mark-bradshaw** [comment]
I'm running MrHorse on an open/open source model, which means anyone who contributes code becomes a collaborator.  I'd very much welcome a pull request with the updated code and any necessary test changes to maintain 100% coverage.

**Comment by PavelPolyakov** [comment]
@mark-bradshaw 
ok, I would.

Just didn't want to commit your code :)

Thanks for the help!

**Comment by mark-bradshaw** [comment]
Just do a PR first, with the code changes and test updates.  If it all
looks good I'll make you a collaborator and you can do updates on your
own.  Just maintain the test coverage and if you have any questions talk it
out.

**Comment by mark-bradshaw** [comment]
https://github.com/mark-bradshaw/mrhorse/pull/10
